using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SourceGeneration;

/// <summary>
/// Generate button name enum by scanning all the `Button` (or `BaseButton`) nodes in the labeled scene.
/// User node's name as enum member name.
/// Generated by sonnet4.5
/// </summary>
[Generator]
public class ButtonEnumGenerator : IIncrementalGenerator
{
    public static readonly string AttributeSourceCode =
        """
        // Generated code from Ciallo. SourceGeneration.ButtonEnumGenerator
        using System;
        namespace Ciallo
        {
            [System.AttributeUsage(System.AttributeTargets.Class)]
            public class ButtonEnumAttribute(string outputEnumName) : Attribute
            {
                public string OutputEnumName { get; } = outputEnumName;
            }
        };
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the attribute source
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "ButtonEnumAttribute.g.cs", AttributeSourceCode));

        // Find all classes with ButtonEnumAttribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Combine with additional files (scene files)
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());
        var additionalFiles = context.AdditionalTextsProvider.Collect();
        var combined = compilationAndClasses.Combine(additionalFiles);

        // Generate the enum
        context.RegisterSourceOutput(combined, static (spc, source) => Execute(source.Left.Left, source.Left.Right, source.Right, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration &&
               classDeclaration.AttributeLists.Count > 0;
    }

    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol;
                if (symbol is not IMethodSymbol attributeSymbol)
                    continue;

                var attributeType = attributeSymbol.ContainingType;
                var attributeTypeName = attributeType.ToDisplayString();
                if (attributeTypeName == "Ciallo.ButtonEnumAttribute" || attributeTypeName == "Ciallo.ButtonEnum")
                {
                    return classDeclaration;
                }
            }
        }

        return null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax?> classes,
        ImmutableArray<AdditionalText> additionalFiles,
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        foreach (var classDeclaration in classes)
        {
            if (classDeclaration is null)
                continue;

            var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

            if (classSymbol is null)
                continue;

            // Get the ButtonEnumAttribute
            var attribute = classSymbol.GetAttributes()
                .FirstOrDefault(a =>
                {
                    var attrTypeName = a.AttributeClass?.ToDisplayString();
                    return attrTypeName == "Ciallo.ButtonEnumAttribute" || attrTypeName == "Ciallo.ButtonEnum";
                });

            if (attribute is null)
                continue;

            // Get the output enum name from attribute constructor argument
            if (attribute.ConstructorArguments.Length == 0 ||
                attribute.ConstructorArguments[0].Value is not string outputEnumName)
                continue;

            var className = classSymbol.Name;

            // Get the SceneTreeAttribute to find the scene file, or infer from class name
            var sceneTreeAttribute = classSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "SceneTreeAttribute");

            string? sceneFilePath = null;
            if (sceneTreeAttribute != null)
            {
                // Get scene file path from SceneTreeAttribute
                if (sceneTreeAttribute.ConstructorArguments.Length > 0)
                {
                    sceneFilePath = sceneTreeAttribute.ConstructorArguments[0].Value as string;
                }
            }
            else
            {
                // Infer scene file path from class name (e.g., ToolButtonPanel -> ToolButtonPanel.tscn)
                sceneFilePath = $"{className}.tscn";
            }

            if (string.IsNullOrEmpty(sceneFilePath))
                continue;

            // Find the scene file in additional files
            var sceneFile = additionalFiles.FirstOrDefault(f =>
                f.Path.EndsWith(sceneFilePath!) || f.Path.EndsWith(sceneFilePath!.Replace("/", "\\")));

            if (sceneFile is null)
                continue;

            // Parse the scene file to extract button nodes
            var sceneContent = sceneFile.GetText(context.CancellationToken);
            if (sceneContent is null)
                continue;

            var buttonNames = ExtractButtonNames(sceneContent.ToString());

            if (buttonNames.Length == 0)
                continue;

            // Generate the enum
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var enumSource = GenerateEnumSource(namespaceName, outputEnumName, buttonNames);
            context.AddSource($"{outputEnumName}.g.cs", enumSource);

            // Generate partial class with conversion methods
            var classSource = GeneratePartialClassSource(namespaceName, className, outputEnumName, buttonNames);
            context.AddSource($"{className}.{outputEnumName}.g.cs", classSource);
        }
    }

    private static ImmutableArray<string> ExtractButtonNames(string sceneContent)
    {
        var buttonNames = ImmutableArray.CreateBuilder<string>();
        var lines = sceneContent.Split('\n');

        foreach (var line in lines)
        {
            var trimmedLine = line.Trim();

            // Check for node definition:  [node name="NodeName" type="Button" ...]
            if (trimmedLine.StartsWith("[node "))
            {
                string? currentNodeName = null;
                bool isButtonNode = false;

                // Extract node name
                var nameStart = trimmedLine.IndexOf("name=\"");
                if (nameStart != -1)
                {
                    nameStart += 6; // Length of "name=\""
                    var nameEnd = trimmedLine.IndexOf("\"", nameStart);
                    if (nameEnd != -1) currentNodeName = trimmedLine.Substring(nameStart, nameEnd - nameStart);
                }

                // Check if it's a Button or BaseButton type
                if (trimmedLine.Contains("type=\"Button\"") ||
                    trimmedLine.Contains("type=\"BaseButton\"") ||
                    trimmedLine.Contains("type=\"TextureButton\"") ||
                    trimmedLine.Contains("type=\"CheckBox\"") ||
                    trimmedLine.Contains("type=\"CheckButton\"") ||
                    trimmedLine.Contains("type=\"ColorPickerButton\"") ||
                    trimmedLine.Contains("type=\"MenuButton\"") ||
                    trimmedLine.Contains("type=\"OptionButton\""))
                {
                    isButtonNode = true;
                }

                // If we found a button node with a valid name, add it
                if (isButtonNode && !string.IsNullOrEmpty(currentNodeName))
                {
                    // Sanitize the name to be a valid C# identifier
                    var sanitizedName = SanitizeIdentifier(currentNodeName!);
                    if (!buttonNames.Contains(sanitizedName))
                    {
                        buttonNames.Add(sanitizedName);
                    }
                }
            }
        }

        return buttonNames.ToImmutable();
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();

        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else if (c == ' ' || c == '-') sb.Append('_');
        }

        var result = sb.ToString();

        // Ensure it starts with a letter or underscore
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "_" + result;
        }

        return string.IsNullOrEmpty(result) ? "_Button" : result;
    }

    private static string GenerateEnumSource(string namespaceName, string enumName, ImmutableArray<string> buttonNames)
    {
        var enumMembers = string.Join(",\n", buttonNames.Select(name => $"        {name}"));

        return $$"""
                 // <auto-generated/>
                 // Generated by ButtonEnumGenerator

                 namespace {{namespaceName}}
                 {
                     public enum {{enumName}}
                     {
                 {{enumMembers}}
                     }
                 }
                 """;
    }

    private static string GeneratePartialClassSource(string namespaceName, string className, string enumName, ImmutableArray<string> buttonNames)
    {
        var switchCasesEnumToButton = string.Join("\n", buttonNames.Select(name =>
            $"            {enumName}.{name} => GetNode<Godot.BaseButton>(\"{name}\"),"));

        var switchCasesButtonToEnum = string.Join("\n", buttonNames.Select(name =>
            $"              \"{name}\" => {enumName}.{name},"));

        return $$"""
                 // <auto-generated/>
                 // Generated by ButtonEnumGenerator

                 using Godot;

                 namespace {{namespaceName}}
                 {
                     public partial class {{className}}
                     {
                         public BaseButton GetButton({{enumName}} button)
                         {
                             return button switch
                             {
                 {{switchCasesEnumToButton}}
                                 _ => throw new System.ArgumentOutOfRangeException(nameof(button), button, null)
                             };
                         }

                         public {{enumName}}? GetButtonEnum(BaseButton button)
                         {
                             if(button == null) return null;
                             return button.Name.ToString() switch
                             {
                 {{switchCasesButtonToEnum}}
                                 _ => null
                             };
                         }
                     }
                 }
                 """;
    }
}