using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneration;

[Generator]
public class CommandBuilderGenerator : IIncrementalGenerator
{
    public static readonly string AttributeSourceCode =
        """
        // <auto-generated/>
        // Generated code from Ciallo.SourceGeneration.CommandBuilderGenerator
        using System;
        namespace Ciallo.Command
        {
            [System.AttributeUsage(System.AttributeTargets.Class)]
            public class CommandBuilderAttribute : Attribute
            {
            }
        };
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "CommandBuilderAttribute.g.cs", AttributeSourceCode));

        IncrementalValuesProvider<CommandToGenerate?> commandsToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Ciallo.Command.CommandBuilderAttribute",
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static commandToGenerate => commandToGenerate is not null);

        context.RegisterSourceOutput(commandsToGenerate, Execute);
    }

    private static void Execute(SourceProductionContext context, CommandToGenerate? source)
    {
        if (source is { } value)
        {
            string result = BuildSourceText(value);
            context.AddSource($"CommandBuilder.{value.CommandMetadataName}.g.cs", SourceText.From(result, Encoding.UTF8));
        }
    }

    private static CommandToGenerate? GetSemanticTarget(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        if (typeSymbol.TypeKind != TypeKind.Class)
            return null;

        var constructors = typeSymbol.InstanceConstructors
            .Where(static ctor => ctor.DeclaredAccessibility == Accessibility.Public && !ctor.IsStatic)
            .Select(CreateConstructor)
            .ToImmutableArray();

        if (constructors.IsDefaultOrEmpty)
            return null;

        string methodName = GetBuilderMethodName(typeSymbol.Name);
        string commandTypeName = typeSymbol.ToDisplayString(CommandTypeFormat);

        ImmutableArray<string> methodTypeParameters = typeSymbol.TypeParameters
            .Select(static p => EscapeIdentifier(p.Name))
            .ToImmutableArray();

        string methodTypeParameterList = methodTypeParameters.IsDefaultOrEmpty
            ? string.Empty
            : $"<{string.Join(", ", methodTypeParameters)}>";

        return new CommandToGenerate(
            methodName,
            typeSymbol.MetadataName,
            commandTypeName,
            methodTypeParameterList,
            constructors);
    }

    private static CommandConstructor CreateConstructor(IMethodSymbol constructorSymbol)
    {
        var parameters = constructorSymbol.Parameters
            .Select(CreateParameter)
            .ToImmutableArray();

        return new CommandConstructor(parameters);
    }

    private static CommandParameter CreateParameter(IParameterSymbol parameterSymbol)
    {
        string declaration = parameterSymbol.ToDisplayString(ParameterFormat);
        string identifier = EscapeIdentifier(parameterSymbol.Name);
        string argumentPrefix = GetArgumentPrefix(parameterSymbol.RefKind);

        return new CommandParameter(declaration, argumentPrefix + identifier);
    }

    private static string GetArgumentPrefix(RefKind refKind)
    {
        if (refKind == RefKind.Ref)
            return "ref ";
        if (refKind == RefKind.Out)
            return "out ";
        if (refKind == RefKind.In)
            return "in ";
        if (refKind == RefKind.RefReadOnly)
            return "ref readonly ";
        return string.Empty;
    }

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;
    }

    private static string GetBuilderMethodName(string commandName)
    {
        const string suffix = "Cmd";
        if (commandName.EndsWith(suffix, StringComparison.Ordinal))
        {
            return commandName.Substring(0, commandName.Length - suffix.Length);
        }

        return commandName;
    }

    private static string BuildSourceText(CommandToGenerate command)
    {
        var builder = new StringBuilder();
        builder.AppendLine(
            """
            // <auto-generated />
            namespace Ciallo.Command;

            public partial class CommandBuilder
            {
            """);

        foreach (CommandConstructor ctor in command.Constructors)
        {
            string parameters = string.Join(", ", ctor.Parameters.Select(p => p.Declaration));
            string arguments = string.Join(", ", ctor.Parameters.Select(p => p.ArgumentExpression));

            builder.AppendLine(
                $$"""
                      public CommandBuilder {{command.BuilderMethodName}}{{command.MethodTypeParameterList}}({{parameters}})
                      {
                          var cmd = new {{command.CommandTypeName}}({{arguments}}) { TargetE = TargetE };
                          Commands.Add(cmd);
                          return this;
                      }

                  """
            );
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static readonly SymbolDisplayFormat CommandTypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                              SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                              SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly SymbolDisplayFormat ParameterFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                              SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                              SymbolDisplayMiscellaneousOptions.UseSpecialTypes,
        parameterOptions: SymbolDisplayParameterOptions.IncludeType |
                          SymbolDisplayParameterOptions.IncludeName |
                          SymbolDisplayParameterOptions.IncludeDefaultValue |
                          SymbolDisplayParameterOptions.IncludeParamsRefOut);
}

public readonly struct CommandToGenerate
{
    public CommandToGenerate(
        string builderMethodName,
        string commandMetadataName,
        string commandTypeName,
        string methodTypeParameterList,
        ImmutableArray<CommandConstructor> constructors)
    {
        BuilderMethodName = builderMethodName;
        CommandMetadataName = commandMetadataName;
        CommandTypeName = commandTypeName;
        MethodTypeParameterList = methodTypeParameterList;
        Constructors = constructors;
    }

    public string BuilderMethodName { get; }
    public string CommandMetadataName { get; }
    public string CommandTypeName { get; }
    public string MethodTypeParameterList { get; }
    public ImmutableArray<CommandConstructor> Constructors { get; }
}

public readonly struct CommandConstructor
{
    public CommandConstructor(ImmutableArray<CommandParameter> parameters)
    {
        Parameters = parameters;
    }

    public ImmutableArray<CommandParameter> Parameters { get; }
}

public readonly struct CommandParameter
{
    public CommandParameter(string declaration, string argumentExpression)
    {
        Declaration = declaration;
        ArgumentExpression = argumentExpression;
    }

    public string Declaration { get; }
    public string ArgumentExpression { get; }
}