using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneration;

/// <summary>
/// Register a tool implementing ITool.
/// For each tool class marked with this attribute, it will be registered in ToolManager's ToolButtonMap.
/// Multiple tools can be registered under the same ToolButton.
/// </summary>
[Generator]
public class RegisterToolGenerator : IIncrementalGenerator
{
    public static readonly string AttributeSourceCode =
        """
        // <auto-generated/>
        // Generated code from Ciallo.SourceGeneration.RegisterToolGenerator

        #nullable enable

        using System;

        namespace Ciallo.Tool;

        // Register a tool class implementing ITool attribute.
        // See ToolManager for usage and implementation details.
        [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        public sealed class RegisterToolAttribute(ToolButton button) : Attribute
        {
            public ToolButton Button { get; } = button;
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "RegisterToolAttribute.g.cs", AttributeSourceCode));

        IncrementalValuesProvider<ImmutableArray<ToolToRegister>> toolsToRegister = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Ciallo.Tool.RegisterToolAttribute",
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetSemanticTargets(ctx));

        var collectedTools = toolsToRegister.SelectMany(static (t, _) => t).Collect();
        context.RegisterSourceOutput(collectedTools, Execute);
    }

    private static ImmutableArray<ToolToRegister> GetSemanticTargets(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return [];

        if (typeSymbol.TypeKind != TypeKind.Class)
            return [];

        var matchingAttributes = ctx.Attributes
            .Where(static a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::Ciallo.Tool.RegisterToolAttribute" ||
                a.AttributeClass?.Name == "RegisterToolAttribute" ||
                a.AttributeClass?.Name == "RegisterTool")
            .ToImmutableArray();

        if (matchingAttributes.Length == 0)
            return [];

        string toolTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var resultBuilder = ImmutableArray.CreateBuilder<ToolToRegister>(matchingAttributes.Length);

        foreach (var attribute in matchingAttributes)
        {
            string? enumMemberName = null;

            if (attribute.ConstructorArguments.Length == 1)
            {
                var toolButtonArg = attribute.ConstructorArguments[0];
                if (toolButtonArg.Kind == TypedConstantKind.Enum && toolButtonArg.Type != null)
                {
                    enumMemberName = GetEnumMemberName(toolButtonArg);
                }
            }

            if (string.IsNullOrEmpty(enumMemberName))
            {
                enumMemberName = GetEnumMemberNameFromSyntax(attribute);
            }

            if (!string.IsNullOrEmpty(enumMemberName))
            {
                string toolButtonEnumMember = $"global::Ciallo.Tool.ToolButton.{enumMemberName}";
                resultBuilder.Add(new ToolToRegister(toolTypeName, toolButtonEnumMember));
            }
        }

        return resultBuilder.ToImmutable();
    }

    private static string? GetEnumMemberNameFromSyntax(AttributeData attribute)
    {
        if (attribute.ApplicationSyntaxReference?.GetSyntax() is not AttributeSyntax syntax)
            return null;

        if (syntax.ArgumentList?.Arguments.Count > 0)
        {
            var expr = syntax.ArgumentList.Arguments[0].Expression;
            if (expr is MemberAccessExpressionSyntax memberAccess)
            {
                return memberAccess.Name.Identifier.Text;
            }
            else if (expr is IdentifierNameSyntax identifier)
            {
                return identifier.Identifier.Text;
            }
        }
        return null;
    }

    private static string GetEnumMemberName(TypedConstant enumConstant)
    {
        if (enumConstant.Type is null)
            return string.Empty;

        var enumType = enumConstant.Type;
        var enumValue = enumConstant.Value;

        if (enumValue is null)
            return string.Empty;

        var members = enumType.GetMembers().OfType<IFieldSymbol>();
        foreach (var member in members)
        {
            if (member.HasConstantValue && member.ConstantValue?.Equals(enumValue) == true)
                return member.Name;
        }

        return enumValue.ToString() ?? string.Empty;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ToolToRegister> tools)
    {
        string sourceCode = BuildSourceText(tools);
        context.AddSource("ToolManager.RegisteredTools.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static string BuildSourceText(ImmutableArray<ToolToRegister> tools)
    {
        var builder = new StringBuilder();
        builder.AppendLine(
            """
            // <auto-generated/>
            // Generated code from Ciallo.SourceGeneration.RegisterToolGenerator

            using System.Collections.Generic;
            using Frent;
            using Frent.Components;

            namespace Ciallo.Tool;

            public partial class ToolManager
            {
                public Dictionary<ToolButton, List<ITool>> InitializeToolButtonMap(Entity document)
                {
                    var result = new Dictionary<ToolButton, List<ITool>>();
            """);

        var groupedTools = tools.GroupBy(static t => t.ToolButton);
        foreach (var group in groupedTools)
        {
            builder.AppendLine($"        result[{group.Key}] = new List<ITool>");
            builder.AppendLine("        {");
            foreach (var tool in group)
                builder.AppendLine($"            new {tool.ToolTypeName}()" + "{Document = document}" + ",");
            builder.AppendLine("        };");
        }

        builder.AppendLine(
            """
                    return result;
                }
            }
            """);

        return builder.ToString();
    }
}

public readonly struct ToolToRegister
{
    public ToolToRegister(string toolTypeName, string toolButton)
    {
        ToolTypeName = toolTypeName;
        ToolButton = toolButton;
    }

    public string ToolTypeName { get; }
    public string ToolButton { get; }
}