using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.Serialization;
using Godot;
using MessagePack;
namespace Ciallo.Geometry;  


/// <summary>
/// This class is a combination of Godot's Curve2D and Curve.
/// Generated by Copilot by referencing Godot C++ code and not strictly verified.
/// </summary>
[DataContract]
public class PolyBezier
{
    #region Curve2D
    // Members from godot's `Curve2D` class.
    [DataContract]
    public struct Point
    {
        [DataMember(Order = 0)] public Vector2 In;        // Incoming control handle relative to position
        [DataMember(Order = 1)] public Vector2 Out;       // Outgoing control handle relative to position
        [DataMember(Order = 2)] public Vector2 Position;  // Main control point
        
        public Point(Vector2 position, Vector2 @in, Vector2 @out)
        {
            Position = position;
            In = @in;
            Out = @out;
        }
        
        public HandleControlMode HandleMode
        {
            get
            {
                bool isEqual = Math.Abs(In.Length() - Out.Length()) < 1e-5f;
                bool isLinear = Math.Abs(In.Angle() + Out.Angle()) < 1e-5f;
                if (isEqual && isLinear)
                    return HandleControlMode.LinearEqual;
                if (isLinear)
                    return HandleControlMode.Linear;
                return HandleControlMode.Free;
            }
            set
            {
                switch (value)
                {
                    case HandleControlMode.LinearEqual:
                        In = -Out;
                        break;
                    case HandleControlMode.Linear:
                        In = -Out.Normalized() * In.Length();
                        break;
                    case HandleControlMode.Free:
                        // Do nothing, already free
                        break;
                    default:
                        throw new ArgumentOutOfRangeException(nameof(value), value, null);
                }
            }
        }
        
        /// <summary>
        /// Shen: Godot's Curve2D's tangent mode is very, very unintuitive. I guess who programed it have never used Adobe Illustrator or Inkscape.
        /// </summary>
        public enum HandleControlMode
        {
            LinearEqual, // Two handles are equal in length and tangent (opposite direction)
            Linear, // Equal in tangent only
            Free
        }
    }
    [DataMember(Order = 0)]
    public IReadOnlyList<Point> Points
    {
        get => _points;
        set
        {
            _points = value.ToList();
            OnChanged();
        }
    }

    private List<Point> _points = [];
    private readonly List<Vector2> _cachedPolyline = [];
    private readonly List<float> _cachedT = []; // Fractional T values for the cached polyline
    private Rect2 _cachedBoundingBox = default;
    
    public int Count => _points.Count;

    public Rect2 BoundingBox
    {
        get
        {
            if (_cachedBoundingBox == default)
            {
                Tessellate();
            }
            return _cachedBoundingBox;
        }
    }
    
    private void OnChanged() => ClearCache();
    public void ClearCache()
    {
        _cachedPolyline.Clear();
        _cachedBoundingBox = default;
        _cachedT.Clear();
    }

    public void AddPoint(Vector2 position, Vector2 inHandle, Vector2 outHandle, int at = -1)
    {
        var point = new Point(position, inHandle, outHandle);
        if (at >= 0 && at < _points.Count)
            _points.Insert(at, point);
        else
            _points.Add(point);
        OnChanged();
    }

    public void RemovePoint(int index)
    {
        if (index >= 0 && index < _points.Count)
        {
            _points.RemoveAt(index);
            OnChanged();
        }
    }

    public void Clear()
    {
        _points.Clear();
        OnChanged();
    }

    public Point GetPoint(int index)
    {
        if (index < 0 || index >= _points.Count) throw new ArgumentOutOfRangeException();
        return _points[index];
    }

    // Sample curve segment at index, t in [0,1]
    public Vector2 Sample(int index, float segT)
    {
        if (_points.Count == 0)
            throw new InvalidOperationException("Cannot sample from an empty curve.");

        if (_points.Count == 1 || index >= _points.Count - 1)
            return _points[^1].Position;

        var p0 = _points[index].Position;
        var p1 = p0 + _points[index].Out;
        var p3 = _points[index + 1].Position;
        var p2 = p3 + _points[index + 1].In;

        return p0.BezierInterpolate(p1, p2, p3, segT);
    }

    // Sample the whole curve at a fractional t (e.g. 2.5 means between segment 2 and 3 at t=0.5)
    public Vector2 Sample(float polyT)
    {
        if (_points.Count == 0)
            throw new InvalidOperationException("Cannot sample from an empty curve.");

        if (polyT < 0)
            polyT = 0;
        else if (polyT >= _points.Count - 1)
            polyT = _points.Count - 1;

        int idx = (int)Math.Floor(polyT);
        float t = polyT - idx;
        return Sample(idx, t);
    }

    /// <summary>
    /// Insert a bezier control point at a fractional t. Do not change the shape of original curve.
    /// </summary>
    public void Split(float polyT)
    {
        if (_points.Count < 2) return;
        // clamp to valid segment range
        if (polyT <= 0f || polyT >= _points.Count - 1) return;
        int idx = (int)Math.Floor(polyT);
        float t = polyT - idx;
        if (t <= 0f || t >= 1f) return;
        // original segment endpoints and controls
        var left = _points[idx];
        var right = _points[idx + 1];
        Vector2 p0 = left.Position;
        Vector2 p1 = p0 + left.Out;
        Vector2 p3 = right.Position;
        Vector2 p2 = p3 + right.In;
        
        var p01 = p0.Lerp(p1, t);
        var p12 = p1.Lerp(p2, t);
        var p23 = p2.Lerp(p3, t);
        var p012 = p01.Lerp(p12, t);
        var p123 = p12.Lerp(p23, t);
        var p0123 = p012.Lerp(p123, t);
        // compute new handles
        left.Out = p01 - p0;
        var newIn = p012 - p0123;
        var newOut = p123 - p0123;
        right.In = p23 - p3;
        // apply changes: update left, insert new, update right
        _points[idx] = left;
        _points.Insert(idx + 1, new Point(p0123, newIn, newOut));
        _points[idx + 2] = right;
        OnChanged();
    }

    /// <summary>
    /// Insert a list of bezier control points at a list of fractional t.
    /// </summary>
    public void Split([NotNull] IReadOnlyList<float> polyT)
    {
        if (_points.Count < 2) return;
        // sort splits descending to avoid index shift issues
        var ts = polyT.Where(t => t > 0f && t < _points.Count - 1)
                   .Distinct()
                   .OrderByDescending(t => t)
                   .ToList();
        foreach (var t in ts) Split(t);
    }
    
    public void Tessellate(int subdivisionsPerSegment = 16)
    {
        ClearCache();
        if (_points.Count == 0)
            return;
        if (_points.Count == 1)
        {
            _cachedPolyline.Add(_points[0].Position);
            return;
        }

        for (int i = 0; i < _points.Count - 1; i++)
        {
            for (int j = 0; j < subdivisionsPerSegment; j++)
            {
                float t = (float)j / subdivisionsPerSegment;
                _cachedPolyline.Add(Sample(i, t));
                _cachedT.Add(i + t);
            }
        }
        // Add the last point
        _cachedPolyline.Add(_points[^1].Position);
        _cachedT.Add(_points.Count - 1);
        _cachedBoundingBox = _cachedPolyline.GetBoundingBox();
    }
    
    /// <summary>
    /// Change the position of an existing point.
    /// </summary>
    public void SetPointPosition(int index, Vector2 position)
    {
        var pt = _points[index];
        pt.Position = position;
        _points[index] = pt;
        OnChanged();
    }

    /// <summary>
    /// Change the incoming handle of an existing point.
    /// </summary>
    public void SetPointIn(int index, Vector2 inHandle)
    {
        var pt = _points[index];
        pt.In = inHandle;
        _points[index] = pt;
        OnChanged();
    }

    /// <summary>
    /// Change the outgoing handle of an existing point.
    /// </summary>
    public void SetPointOut(int index, Vector2 outHandle)
    {
        var pt = _points[index];
        pt.Out = outHandle;
        _points[index] = pt;
        OnChanged();
    }

    /// <summary>
    /// Get the closest point on the curve to a given point p.
    /// </summary>
    /// <returns>Point position, output fractional t of the close point</returns>
    public Vector2 GetClosestPoint(Vector2 p, out float t)
    {
        if(_cachedT.Count == 0)
        {
            Tessellate();
        }
        _cachedPolyline.GetClosestPoint(p, out var polyT);
        var polyI = (int)MathF.Floor(polyT);
        if(polyI >= _cachedT.Count - 1)
        {
            t = _cachedT[^1];
            return _cachedPolyline[^1];
        }
        var deltaT = (polyT - polyI) * (_cachedT[polyI + 1] - _cachedT[polyI]);
        t = _cachedT[polyI] + deltaT;
        return Sample(t);
    }
    #endregion

    #region Curve
    
    // Members from Godot's `Curve` class.
    public float MinDomain
    {
        get
        {
            if(_cachedBoundingBox == default) Tessellate();
            return _cachedBoundingBox.Position.X;
        }
    }
    public float MaxDomain
    {
        get
        {
            if(_cachedBoundingBox == default) Tessellate();
            return _cachedBoundingBox.End.X;
        }
    }
    public float MinValue
    {
        get
        {
            if(_cachedBoundingBox == default) Tessellate();
            return _cachedBoundingBox.Position.Y;
        }
    }
    
    public float MaxValue
    {
        get
        {
            if(_cachedBoundingBox == default) Tessellate();
            return _cachedBoundingBox.End.Y;
        }
    } 
    public float ValueRange => MaxValue - MinValue;
    public float DomainRange => MaxDomain - MinDomain;

    /// <summary>
    /// Check if the curve is a monotone in X.
    /// So that each element of the function's domain X maps to a single element of its range Y.
    /// </summary>
    public bool IsXMonotone
    {
        get
        {
            if (_cachedPolyline.Count == 0) Tessellate();
            return _cachedPolyline.IsXMonotone();
        }
    }

    /// <summary>
    /// Returns the Y value for the point at the X position.
    /// </summary>
    public float SampleX(float x)
    {
        if (_cachedPolyline.Count == 0) Tessellate();
        return _cachedPolyline.SampleX(x);
    }

    #endregion
}