using System;
using System.Collections.Generic;
using Godot;
using MessagePack;
namespace Ciallo.Geometry;


/// <summary>
/// This class is a combination of Godot's Curve2D and Curve.
/// Generated by Copilot by referencing Godot C++ code and not strictly verified.
/// </summary>
public class Curve2D
{
    #region Curve2D
    [MessagePackObject]
    public struct Point
    {
        [Key(0)] public Vector2 In;        // Incoming control handle relative to position
        [Key(1)] public Vector2 Out;       // Outgoing control handle relative to position
        [Key(2)] public Vector2 Position;  // Main control point

        public Point(Vector2 position, Vector2 @in, Vector2 @out)
        {
            Position = position;
            In = @in;
            Out = @out;
        }
    }

    public readonly List<Point> Points = [];
    
    private readonly List<Vector2> _cachedPolyline = [];
    private readonly List<float> _cachedT = []; // Fractional T values for the cached polyline
    private Rect2 _cachedBoundingBox = default;

    public int Count => Points.Count;

    public Rect2 BoundingBox
    {
        get
        {
            if (_cachedBoundingBox == default)
            {
                Tessellate();
            }
            return _cachedBoundingBox;
        }
    }
    
    private void OnChanged() => ClearCache();
    public void ClearCache()
    {
        _cachedPolyline.Clear();
        _cachedBoundingBox = default;
        _cachedT.Clear();
    }

    public void AddPoint(Vector2 position, Vector2 inHandle, Vector2 outHandle, int at = -1)
    {
        var point = new Point(position, inHandle, outHandle);
        if (at >= 0 && at < Points.Count)
            Points.Insert(at, point);
        else
            Points.Add(point);
        OnChanged();
    }

    public void RemovePoint(int index)
    {
        if (index >= 0 && index < Points.Count)
        {
            Points.RemoveAt(index);
            OnChanged();
        }
    }

    public void Clear()
    {
        Points.Clear();
        OnChanged();
    }

    public Point GetPoint(int index)
    {
        if (index < 0 || index >= Points.Count) throw new ArgumentOutOfRangeException();
        return Points[index];
    }

    // Sample curve segment at index, t in [0,1]
    public Vector2 Sample(int index, float segT)
    {
        if (Points.Count == 0)
            return new Vector2(0, 0);

        if (Points.Count == 1 || index >= Points.Count - 1)
            return Points[^1].Position;

        var p0 = Points[index].Position;
        var p1 = p0 + Points[index].Out;
        var p3 = Points[index + 1].Position;
        var p2 = p3 + Points[index + 1].In;

        return p0.BezierInterpolate(p1, p2, p3, segT);
    }

    // Sample the whole curve at a fractional t (e.g. 2.5 means between segment 2 and 3 at t=0.5)
    public Vector2 Sample(float polyT)
    {
        if (Points.Count == 0)
            return new Vector2(0, 0);

        if (polyT < 0)
            polyT = 0;
        else if (polyT >= Points.Count - 1)
            polyT = Points.Count - 1;

        int idx = (int)Math.Floor(polyT);
        float t = polyT - idx;
        return Sample(idx, t);
    }

    // For display: Returns a polyline that tessellates the curve with n subdivisions per segment
    public void Tessellate(int subdivisionsPerSegment = 16)
    {
        _cachedPolyline.Clear();
        if (Points.Count == 0)
            return;
        if (Points.Count == 1)
        {
            _cachedPolyline.Add(Points[0].Position);
            return;
        }

        for (int i = 0; i < Points.Count - 1; i++)
        {
            for (int j = 0; j < subdivisionsPerSegment; j++)
            {
                float t = (float)j / subdivisionsPerSegment;
                _cachedPolyline.Add(Sample(i, t));
                _cachedT.Add(i + t);
            }
        }
        // Add the last point
        _cachedPolyline.Add(Points[^1].Position);
        _cachedT.Add(Points.Count - 1);
        _cachedBoundingBox = _cachedPolyline.GetBoundingBox();
    }
    
    /// <summary>
    /// Change the position of an existing point.
    /// </summary>
    public void SetPointPosition(int index, Vector2 position)
    {
        if (index < 0 || index >= Points.Count)
            throw new ArgumentOutOfRangeException(nameof(index));
        var pt = Points[index];
        pt.Position = position;
        Points[index] = pt;
        OnChanged();
    }

    /// <summary>
    /// Change the incoming handle of an existing point.
    /// </summary>
    public void SetPointIn(int index, Vector2 inHandle)
    {
        if (index < 0 || index >= Points.Count)
            throw new ArgumentOutOfRangeException(nameof(index));
        var pt = Points[index];
        pt.In = inHandle;
        Points[index] = pt;
        OnChanged();
    }

    /// <summary>
    /// Change the outgoing handle of an existing point.
    /// </summary>
    public void SetPointOut(int index, Vector2 outHandle)
    {
        if (index < 0 || index >= Points.Count)
            throw new ArgumentOutOfRangeException(nameof(index));
        var pt = Points[index];
        pt.Out = outHandle;
        Points[index] = pt;
        OnChanged();
    }

    /// <summary>
    /// Get the closest point on the curve to a given point p.
    /// </summary>
    /// <returns>Point position, output fractional t of the close point</returns>
    public Vector2 GetClosestPoint(Vector2 p, out float t)
    {
        if(_cachedT.Count == 0)
        {
            Tessellate();
        }
        _cachedPolyline.GetClosestPoint(p, out var polyT);
        var polyI = (int)MathF.Floor(polyT);
        if(polyI >= _cachedT.Count - 1)
        {
            t = _cachedT[^1];
            return _cachedPolyline[^1];
        }
        var deltaT = (polyT - polyI) * (_cachedT[polyI + 1] - _cachedT[polyI]);
        t = _cachedT[polyI] + deltaT;
        return Sample(t);
    }
    #endregion

    // #region Curve
    //
    //
    //
    // #endregion
}