using System;
using Godot;

namespace Ciallo.Tool;

public readonly record struct LiquifyDab(
    Vector2 Center,
    Vector2 Delta,
    float Radius,
    float Strength,
    float Pressure);

/// <remarks>
/// Generated by GPT-5.5 by asking it to learn from the code of Blender grease pencil's "Sculpt" tool.
/// </remarks>
public static class LiquifySculpt
{
    // Per-dab radial scaling for Expand/Pinch. With influence ≤ 1, peak per-dab
    // displacement is (1/5)² = 4%, so a drag accumulates smoothly instead of
    // snapping the geometry on a single dab.
    private const float RadialEffectScale = 1f / 5f;

    public static Vector2 Apply(LiquifyMode mode, Vector2 position, LiquifyDab dab)
    {
        float influence = Influence(position, dab);
        if (influence <= 0f)
            return position;

        return mode switch
        {
            LiquifyMode.Push => Push(position, dab.Delta, influence),
            LiquifyMode.Expand => Expand(position, dab.Center, influence),
            LiquifyMode.Pinch => Pinch(position, dab.Center, influence),
            _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, null)
        };
    }

    public static float Influence(Vector2 position, LiquifyDab dab)
    {
        float distance = position.DistanceTo(dab.Center);
        if (distance > dab.Radius)
            return 0f;

        float falloff = SmoothFalloff(distance / dab.Radius);
        return dab.Strength * NormalizePressure(dab.Pressure) * falloff;
    }

    private static Vector2 Push(Vector2 position, Vector2 brushDelta, float influence)
    {
        return position + brushDelta * influence;
    }

    private static Vector2 Expand(Vector2 position, Vector2 brushCenter, float influence)
    {
        float scaled = influence * RadialEffectScale;
        float factor = 1f + scaled * scaled;
        return brushCenter + (position - brushCenter) * factor;
    }

    private static Vector2 Pinch(Vector2 position, Vector2 brushCenter, float influence)
    {
        float scaled = influence * RadialEffectScale;
        float factor = 1f - scaled * scaled;
        return brushCenter + (position - brushCenter) * factor;
    }

    private static float SmoothFalloff(float normalizedDistance)
    {
        float t = Mathf.Clamp(normalizedDistance, 0f, 1f);
        return 1f - t * t * (3f - 2f * t);
    }

    private static float NormalizePressure(float pressure) => pressure <= 0f ? 1f : pressure;
}
